# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

# config/routes.yaml
auth_login_check:
    path: /auth/login_check

# Handle browser preflight request
# hhttps://fetch.spec.whatwg.org/#http-requests
api_cors_preflight:
    path: '/{route_path}'
    controller: Api\Controller\Technical\CorsController::preflight
    methods: ['OPTIONS']
    condition: '(request.headers.all()["access-control-request-method"] ?? null) != null and (request.headers.all()["access-control-request-headers"] ?? null) != null'
